// Code generated by tools/releases/generate_errors.py; DO NOT EDIT.
package wire

func UpdateErrorName(domain, reason uint16) string {
	switch uint32(domain)<<16 | uint32(reason) {
	case 0:
		return "OK"
	case 65537:
		return "NETWORK_UNAVAILABLE"
	case 65538:
		return "NETWORK_NOT_FOUND"
	case 65539:
		return "NETWORK_TIME_UNAVAILABLE"
	case 131073:
		return "META_MALFORMED"
	case 131074:
		return "META_BAD_SIGNATURE"
	case 131075:
		return "META_EXPIRED"
	case 131076:
		return "META_REPLAY"
	case 131077:
		return "META_TRUST_UNCONFIGURED"
	case 131078:
		return "META_ROOT_ROTATION_PENDING"
	case 196609:
		return "ELIGIBILITY_HARDWARE_UNKNOWN"
	case 196610:
		return "ELIGIBILITY_INCOMPATIBLE"
	case 196611:
		return "ELIGIBILITY_ROLLOUT_EXCLUDED"
	case 262145:
		return "ARTIFACT_BAD_SIGNATURE"
	case 327681:
		return "STORAGE_UNAVAILABLE"
	case 393217:
		return "SAFETY_DURABILITY_UNAVAILABLE"
	case 393218:
		return "SAFETY_ACK_TIMEOUT"
	case 458753:
		return "TRIAL_ROLLED_BACK"
	default:
		return "UPDATE_UNKNOWN_ERROR"
	}
}
