package main

import (
	"bytes"
	"context"
	"encoding/hex"
	"fmt"
	"io"
	"log/slog"
	"os"
	"testing"
	"time"

	"github.com/ptudor/navlistener/internal/config"
	"github.com/ptudor/navlistener/internal/ingest"
	"github.com/ptudor/navlistener/internal/store"
)

// Equal-body frames use independent CRC fixtures generated by Python's
// binascii.crc_hqx over the documented SBF ID+length+body fields.
func sbfCaptureFixtures(t *testing.T) ([][]byte, []*store.NavFrame) {
	t.Helper()
	source := fmt.Sprintf("sbf-revision-%d", time.Now().UnixNano())
	now := time.Now().UTC().Truncate(time.Microsecond)
	var wires [][]byte
	for _, s := range []string{"24408b7ab12f1800000102030405060708090a0b0c0d0e0f", "24408c49b1cf1800000102030405060708090a0b0c0d0e0f"} {
		b, e := hex.DecodeString(s)
		if e != nil {
			t.Fatal(e)
		}
		wires = append(wires, b)
	}
	var frames []*store.NavFrame
	err := ingest.ReplaySBF(bytes.NewReader(bytes.Join(wires, nil)), source, func() time.Time { return now }, func(f *ingest.RawFrame) {
		frames = append(frames, frameForPersistence(f))
	}, func(kind string) { t.Errorf("scan: %s", kind) })
	if err != nil || len(frames) != 2 {
		t.Fatalf("scanner frames=%d err=%v", len(frames), err)
	}
	return wires, frames
}
func assertSBFCapture(t *testing.T, f store.StoredNavFrame, want []byte, rev uint8) {
	t.Helper()
	if f.MsgType != 4017 {
		t.Fatalf("block number changed: %d", f.MsgType)
	}
	restored, err := ingest.RestoreSBF(f.MsgType, f.Raw, f.SBFHeader)
	if err != nil {
		t.Fatal(err)
	}
	got, known := restored.SBFRevision()
	if !known || got != rev {
		t.Fatalf("revision %d known=%v want=%d", got, known, rev)
	}
	wire, err := restored.SBFWire()
	if err != nil || !bytes.Equal(wire, want) {
		t.Fatalf("wire differs: %x %v", wire, err)
	}
}
func TestSBFCapturePersistenceMapping(t *testing.T) {
	wires, frames := sbfCaptureFixtures(t)
	for i, f := range frames {
		assertSBFCapture(t, store.StoredNavFrame{MsgType: f.MsgType, Raw: f.Raw, SBFHeader: f.SBFHeader}, wires[i], []uint8{1, 6}[i])
	}
	if !bytes.Equal(frames[0].Raw, frames[1].Raw) {
		t.Fatal("body changed")
	}
	if bytes.Equal(frames[0].SBFHeader, frames[1].SBFHeader) {
		t.Fatal("revisions lost")
	}
	legacy, err := ingest.RestoreSBF(4017, frames[0].Raw, nil)
	if err != nil {
		t.Fatal(err)
	}
	if _, known := legacy.SBFRevision(); known {
		t.Fatal("invented legacy revision")
	}
	if _, err := legacy.SBFWire(); err == nil {
		t.Fatal("invented legacy header")
	}
	for _, bad := range []struct {
		block        int
		body, header []byte
	}{
		{4018, frames[0].Raw, frames[0].SBFHeader},
		{4017, []byte{0, 1, 2, 3}, frames[0].SBFHeader},
		{4017, frames[0].Raw, frames[0].SBFHeader[:7]},
	} {
		if _, err := ingest.RestoreSBF(bad.block, bad.body, bad.header); err == nil {
			t.Fatal("accepted damaged metadata")
		}
	}
}
func TestIntegrationSBFHeaderRoundTrip(t *testing.T) {
	dsn := os.Getenv("NAVLISTENER_TEST_DSN")
	if dsn == "" {
		t.Skip("NAVLISTENER_TEST_DSN not set")
	}
	wires, frames := sbfCaptureFixtures(t)
	ctx := context.Background()
	s, err := store.New(ctx, config.Store{DSN: dsn, BatchSize: 100, BatchEvery: time.Second, RawRetention: "7 days", CompressAfter: "1 day"}, slog.New(slog.NewTextHandler(io.Discard, nil)))
	if err != nil {
		t.Fatal(err)
	}
	for _, f := range frames {
		s.Enqueue(f)
	}
	legacy := *frames[0]
	legacy.SBFHeader = nil
	s.Enqueue(&legacy)
	runCtx, cancel := context.WithCancel(ctx)
	cancel()
	s.Run(runCtx) // normal shutdown drains and closes writer
	r, err := store.OpenReader(ctx, dsn)
	if err != nil {
		t.Fatal(err)
	}
	defer r.Close()
	count := 0
	seen := map[uint8]bool{}
	err = r.QueryNavFrames(ctx, store.NavFrameQuery{Since: frames[0].ReceivedAt.Add(-time.Second), Until: frames[0].ReceivedAt.Add(time.Second), SourceID: frames[0].SourceID}, func(f store.StoredNavFrame) error {
		count++
		restored, e := ingest.RestoreSBF(f.MsgType, f.Raw, f.SBFHeader)
		if e != nil {
			return e
		}
		rev, known := restored.SBFRevision()
		if !known {
			if _, e = restored.SBFWire(); e == nil {
				t.Fatal("legacy wire invented")
			}
			return nil
		}
		idx := 0
		if rev == 6 {
			idx = 1
		}
		assertSBFCapture(t, f, wires[idx], []uint8{1, 6}[idx])
		seen[rev] = true
		return nil
	})
	if err != nil || count != 3 || !seen[1] || !seen[6] {
		t.Fatalf("count=%d revisions=%v err=%v", count, seen, err)
	}
}
