#!/usr/bin/env python3
"""Generate stable firmware/collector error names from the shared registry."""
import argparse
import json
from pathlib import Path
import subprocess

ROOT = Path(__file__).resolve().parents[2]

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rows = json.loads((ROOT / "common/update-errors.json").read_bytes())
    assert len({(r["domain"], r["reason"]) for r in rows}) == len(rows)
    c = "// Generated by tools/releases/generate_errors.py; edit common/update-errors.json.\n"
    go = "// Code generated by tools/releases/generate_errors.py; DO NOT EDIT.\npackage wire\n\nfunc UpdateErrorName(domain, reason uint16) string {\n switch uint32(domain)<<16|uint32(reason) {\n"
    for r in rows:
        c += f'NVF_UPDATE_ERROR({r["symbol"]},{r["domain"]},{r["reason"]},"{r["name"]}")\n'
        go += f' case {r["domain"] * 65536 + r["reason"]}: return "{r["name"]}"\n'
    go += ' default: return "UPDATE_UNKNOWN_ERROR"\n }\n}\n'
    go = subprocess.run(["gofmt"], input=go.encode(), stdout=subprocess.PIPE, check=True).stdout
    for path, data in (("esp32/components/ota/include/update_errors.inc", c.encode()), ("go/internal/wire/update_errors.go", go)):
        target = ROOT / path
        if args.check:
            if not target.is_file() or target.read_bytes() != data:
                raise SystemExit(f"stale generated registry: {path}")
        else:
            target.write_bytes(data)

if __name__ == "__main__":
    main()
